version: "3.3"
services:
  backend:
    build: .
    image: youtube_analytics-backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - .env

